---
permalink: /blog/:categories/:year/:month/:day/:title.html
url: "http://fresco-cn.org"
# url: "http://localhost:4000"
baseurl: ""
origin_url: "http://frescolib.org"
title: Fresco
tagline: 专为ANDROID加载图片
fbappid: "1615782811974223"
gacode: "UA-44373548-3"
relative_permalinks: false
description: >
  Fresco 是一个强大的图片加载组件。使用它之后，你不需要再去关心图片的加载和显示这些繁琐的事情！ 支持 Android 2.3 及以后的版本。
timezone: Asia/Shanghai
ghrepo: "facebook/fresco"
ghrepo_doc: "desmond1121/fresco-docs-cn"

current_version: 0.12.0

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: :compressed

collections:
  docs:
    output: true
    permalink: /docs/:name/
  support:
    output: true
    permalink: /support/

color:
  primary: "#db6130"
  secondary: "#f9f9f9"
  # Use the following to specify whether the previous two colours are 'light'
  # or 'dark'
  primary-overlay: "dark"
  secondary-overlay: "light"
